//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class APGLControlAcct
    {
        public int APGLControlAcctID { get; set; }
        public Nullable<int> GLAccountID { get; set; }
        public string GLAccountNo { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
