//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class APInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APInvoice()
        {
            this.APInvoiceDetails = new HashSet<APInvoiceDetail>();
        }
    
        public long APInvoiceID { get; set; }
        public Nullable<int> APVendorID { get; set; }
        public Nullable<System.DateTime> APInvoiceDate { get; set; }
        public string APInvoiceNo { get; set; }
        public Nullable<decimal> APInvoiceAmount { get; set; }
        public Nullable<decimal> APTaxAmount { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APInvoiceDetail> APInvoiceDetails { get; set; }
        public virtual APVendor APVendor { get; set; }
    }
}
