//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKBankTransDetail
    {
        public long BankTransDetID { get; set; }
        public Nullable<long> BankTransID { get; set; }
        public Nullable<int> BankTransTypeID { get; set; }
        public string TransDescription { get; set; }
        public string DocumentRef { get; set; }
        public Nullable<short> A1 { get; set; }
        public Nullable<short> A2 { get; set; }
        public Nullable<short> A3 { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public Nullable<short> IsPost { get; set; }
        public Nullable<int> APVendorID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
