//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVApplicationForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DVApplicationForm()
        {
            this.DVApplicants = new HashSet<DVApplicant>();
            this.DVDocuments = new HashSet<DVDocument>();
            this.DVReceipts = new HashSet<DVReceipt>();
        }
    
        public int ApplicationFormID { get; set; }
        public string ApplicationFormNo { get; set; }
        public Nullable<System.DateTime> ApplicationFormDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ExtraSQFT { get; set; }
        public Nullable<decimal> TokenMoney { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> PossessionStatus { get; set; }
        public Nullable<System.DateTime> PossessionDate { get; set; }
        public string A4 { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int CompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVApplicant> DVApplicants { get; set; }
        public virtual DVUnit DVUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVDocument> DVDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVReceipt> DVReceipts { get; set; }
    }
}
