//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVApplicant
    {
        public int ApplicantID { get; set; }
        public Nullable<int> ApplicationFormID { get; set; }
        public string Name { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string HusbandFather { get; set; }
        public string NICOP_CNIC { get; set; }
        public string Passport { get; set; }
        public string HouseNo { get; set; }
        public string StreetArea { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Division { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string Country { get; set; }
        public string CorrespondenceAdressHouseNo { get; set; }
        public string StreetArea2 { get; set; }
        public string City2 { get; set; }
        public string Country2 { get; set; }
        public string PhoneNo { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Email { get; set; }
        public string Profession { get; set; }
        public string SubProfession { get; set; }
        public string Living { get; set; }
        public string Citizen { get; set; }
        public string Tax { get; set; }
        public string NomioneeName { get; set; }
        public string NomineeFatherHusbandName { get; set; }
        public string Nominee_NICOP_CNIC { get; set; }
        public string Relation { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual DVApplicationForm DVApplicationForm { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Province Province { get; set; }
    }
}
