//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVDocumentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DVDocumentType()
        {
            this.DVDocuments = new HashSet<DVDocument>();
        }
    
        public int DocumentTypeID { get; set; }
        public string DocumentTypeName { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVDocument> DVDocuments { get; set; }
    }
}
