//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVPaymentPlan
    {
        public int PaymentPlanID { get; set; }
        public Nullable<System.DateTime> PaymentPlanDate { get; set; }
        public Nullable<int> ApplicationFormID { get; set; }
        public Nullable<System.DateTime> PaymentStartDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
