//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVPaymentPackage
    {
        public int PaymentPackageID { get; set; }
        public string PaymentPackageName { get; set; }
        public Nullable<int> DP { get; set; }
        public Nullable<int> INS { get; set; }
        public Nullable<int> PS { get; set; }
        public Nullable<int> NoOfInstallments { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
