//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DVReceipt()
        {
            this.DVReceiptDetails = new HashSet<DVReceiptDetail>();
        }
    
        public int DVReceiptID { get; set; }
        public Nullable<int> ApplicationFormID { get; set; }
        public Nullable<System.DateTime> DVReceiptDate { get; set; }
        public Nullable<bool> Varified { get; set; }
        public Nullable<int> VarifiedBy { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual DVApplicationForm DVApplicationForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVReceiptDetail> DVReceiptDetails { get; set; }
    }
}
