//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVReceiptDetail
    {
        public long DVReceiptDetailID { get; set; }
        public Nullable<int> DVReceiptID { get; set; }
        public Nullable<int> PaymentPlanTypeID { get; set; }
        public Nullable<int> DVPaymentMethodID { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual DVPaymentMethod DVPaymentMethod { get; set; }
        public virtual DVReceipt DVReceipt { get; set; }
    }
}
