//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DVUnit()
        {
            this.DVApplicationForms = new HashSet<DVApplicationForm>();
        }
    
        public int UnitID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string UnitNo { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public string FloorNo { get; set; }
        public Nullable<int> SQFT { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public Nullable<short> DVArrangementTypeID { get; set; }
        public Nullable<bool> Onhold { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Matrix { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVApplicationForm> DVApplicationForms { get; set; }
        public virtual DVProject DVProject { get; set; }
        public virtual DVUnitType DVUnitType { get; set; }
    }
}
