//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLCostCenterDetail
    {
        public int GLCostCenterDetailID { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string SubDesc { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
