//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLNature
    {
        public int GLNatureID { get; set; }
        public string A1 { get; set; }
        public string A2 { get; set; }
        public string Nature { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
