//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INItem()
        {
            this.INGoodsReceiptNoteDetails = new HashSet<INGoodsReceiptNoteDetail>();
            this.INProjectItems = new HashSet<INProjectItem>();
            this.INPurchaseRequisitionDetails = new HashSet<INPurchaseRequisitionDetail>();
            this.INStoreIssueNoteDetails = new HashSet<INStoreIssueNoteDetail>();
            this.INStoreTransferNoteDetails = new HashSet<INStoreTransferNoteDetail>();
            this.INStoreReturnNoteDetails = new HashSet<INStoreReturnNoteDetail>();
        }
    
        public long ItemID { get; set; }
        public Nullable<long> ItemCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> UOMID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> Freeze { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual INCategory INCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INGoodsReceiptNoteDetail> INGoodsReceiptNoteDetails { get; set; }
        public virtual INGroup INGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INProjectItem> INProjectItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INPurchaseRequisitionDetail> INPurchaseRequisitionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INStoreIssueNoteDetail> INStoreIssueNoteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INStoreTransferNoteDetail> INStoreTransferNoteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INStoreReturnNoteDetail> INStoreReturnNoteDetails { get; set; }
        public virtual INSize INSize { get; set; }
        public virtual INUnitOfMeasurement INUnitOfMeasurement { get; set; }
    }
}
