//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPORevertHistory
    {
        public long PORevertHistoryID { get; set; }
        public Nullable<long> PurchaseOrderID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> SrNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> RevertedDate { get; set; }
        public Nullable<decimal> RevertedQty { get; set; }
        public Nullable<decimal> RevertedRate { get; set; }
        public Nullable<decimal> RevertedDiscount { get; set; }
        public Nullable<decimal> RevertedTotalAmount { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
