//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPurchaseRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INPurchaseRequisition()
        {
            this.INPurchaseRequisitionDetails = new HashSet<INPurchaseRequisitionDetail>();
        }
    
        public long RequestID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<long> DocumentNo { get; set; }
        public Nullable<long> ManualDemandNo { get; set; }
        public string ProjectDocumentNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SubmitedByKPO { get; set; }
        public Nullable<System.DateTime> SubmitedAtKPO { get; set; }
        public Nullable<int> SubmitedByMD { get; set; }
        public Nullable<System.DateTime> SubmitedAtMD { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledAt { get; set; }
        public Nullable<int> RequestTypeID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INPurchaseRequisitionDetail> INPurchaseRequisitionDetails { get; set; }
        public virtual INRequestType INRequestType { get; set; }
    }
}
