//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPurchaseOrder
    {
        public long PurchaseOrderID { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public Nullable<long> RequestID { get; set; }
        public Nullable<long> GoodsReceiptNoteID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> APVendorID { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledAt { get; set; }
        public Nullable<int> POStatusID { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> FreightCharges { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
