//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INStoreIssueNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INStoreIssueNote()
        {
            this.INStoreIssueNoteDetails = new HashSet<INStoreIssueNoteDetail>();
        }
    
        public long StoreIssueNoteID { get; set; }
        public Nullable<System.DateTime> StoreIssueNoteDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual INStore INStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INStoreIssueNoteDetail> INStoreIssueNoteDetails { get; set; }
    }
}
