//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INStoreIssueNoteDetail
    {
        public long StoreIssueNoteDetailID { get; set; }
        public Nullable<long> StoreIssueNoteID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<decimal> IssuedQty { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual INStoreIssueNote INStoreIssueNote { get; set; }
        public virtual INItem INItem { get; set; }
    }
}
