//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INStoreTransferNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INStoreTransferNote()
        {
            this.INStoreTransferNoteDetails = new HashSet<INStoreTransferNoteDetail>();
        }
    
        public long StoreTransferNoteID { get; set; }
        public Nullable<System.DateTime> StoreTransferNoteDate { get; set; }
        public Nullable<int> FromProjectID { get; set; }
        public Nullable<int> ToProjectID { get; set; }
        public string RefOGPNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ApprovedByID { get; set; }
        public Nullable<System.DateTime> ApprovedByAt { get; set; }
        public Nullable<int> ReceivedByID { get; set; }
        public Nullable<System.DateTime> ReceivedByAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INStoreTransferNoteDetail> INStoreTransferNoteDetails { get; set; }
    }
}
