//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GLEntities : DbContext
    {
        public GLEntities()
            : base("name=GLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APGLControlAcct> APGLControlAccts { get; set; }
        public virtual DbSet<APInvoice> APInvoices { get; set; }
        public virtual DbSet<APInvoiceDetail> APInvoiceDetails { get; set; }
        public virtual DbSet<BKBank> BKBanks { get; set; }
        public virtual DbSet<BKBankTran> BKBankTrans { get; set; }
        public virtual DbSet<BKBankTransDetail> BKBankTransDetails { get; set; }
        public virtual DbSet<BKBankTransType> BKBankTransTypes { get; set; }
        public virtual DbSet<BSBankStatement> BSBankStatements { get; set; }
        public virtual DbSet<BSClassification> BSClassifications { get; set; }
        public virtual DbSet<BSClassificationDetail> BSClassificationDetails { get; set; }
        public virtual DbSet<BSClassificationType> BSClassificationTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<DVApplicant> DVApplicants { get; set; }
        public virtual DbSet<DVApplicationForm> DVApplicationForms { get; set; }
        public virtual DbSet<DVArrangementType> DVArrangementTypes { get; set; }
        public virtual DbSet<DVDocument> DVDocuments { get; set; }
        public virtual DbSet<DVDocumentType> DVDocumentTypes { get; set; }
        public virtual DbSet<DVOBilling> DVOBillings { get; set; }
        public virtual DbSet<DVOBillingDetail> DVOBillingDetails { get; set; }
        public virtual DbSet<DVPaymentMethod> DVPaymentMethods { get; set; }
        public virtual DbSet<DVPaymentPackage> DVPaymentPackages { get; set; }
        public virtual DbSet<DVPaymentPlan> DVPaymentPlans { get; set; }
        public virtual DbSet<DVPaymentPlanDetail> DVPaymentPlanDetails { get; set; }
        public virtual DbSet<DVPaymentPlanType> DVPaymentPlanTypes { get; set; }
        public virtual DbSet<DVProject> DVProjects { get; set; }
        public virtual DbSet<DVReceipt> DVReceipts { get; set; }
        public virtual DbSet<DVReceiptDetail> DVReceiptDetails { get; set; }
        public virtual DbSet<DVUnit> DVUnits { get; set; }
        public virtual DbSet<DVUnitType> DVUnitTypes { get; set; }
        public virtual DbSet<FiscalYearSetup> FiscalYearSetups { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GLAccount> GLAccounts { get; set; }
        public virtual DbSet<GLCostCenterDetail> GLCostCenterDetails { get; set; }
        public virtual DbSet<GLCostCenterMaster> GLCostCenterMasters { get; set; }
        public virtual DbSet<GLGroup> GLGroups { get; set; }
        public virtual DbSet<GLNature> GLNatures { get; set; }
        public virtual DbSet<GLOpeningBalance> GLOpeningBalances { get; set; }
        public virtual DbSet<GLVoucher> GLVouchers { get; set; }
        public virtual DbSet<GLVoucherDetail> GLVoucherDetails { get; set; }
        public virtual DbSet<INCategory> INCategories { get; set; }
        public virtual DbSet<INGroup> INGroups { get; set; }
        public virtual DbSet<INRequestType> INRequestTypes { get; set; }
        public virtual DbSet<INStoreIssueNote> INStoreIssueNotes { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<SecModule> SecModules { get; set; }
        public virtual DbSet<SecPage> SecPages { get; set; }
        public virtual DbSet<SecPagesRight> SecPagesRights { get; set; }
        public virtual DbSet<SecRole> SecRoles { get; set; }
        public virtual DbSet<SecUserRole> SecUserRoles { get; set; }
        public virtual DbSet<SecUser> SecUsers { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
        public virtual DbSet<VoucherType> VoucherTypes { get; set; }
        public virtual DbSet<INStoreTransferNote> INStoreTransferNotes { get; set; }
        public virtual DbSet<INProjectItem> INProjectItems { get; set; }
        public virtual DbSet<INProject> INProjects { get; set; }
        public virtual DbSet<INStore> INStores { get; set; }
        public virtual DbSet<INPurchaseRequisition> INPurchaseRequisitions { get; set; }
        public virtual DbSet<INPurchaseRequisitionDetail> INPurchaseRequisitionDetails { get; set; }
        public virtual DbSet<INStoreIssueNoteDetail> INStoreIssueNoteDetails { get; set; }
        public virtual DbSet<INStoreTransferNoteDetail> INStoreTransferNoteDetails { get; set; }
        public virtual DbSet<APVendorCategory> APVendorCategories { get; set; }
        public virtual DbSet<INPOStatu> INPOStatus { get; set; }
        public virtual DbSet<INGoodsReceiptNoteDetail> INGoodsReceiptNoteDetails { get; set; }
        public virtual DbSet<INGoodsReceiptNote> INGoodsReceiptNotes { get; set; }
        public virtual DbSet<INPurchaseOrder> INPurchaseOrders { get; set; }
        public virtual DbSet<APVendor> APVendors { get; set; }
        public virtual DbSet<INPurchaseOrderDetail> INPurchaseOrderDetails { get; set; }
        public virtual DbSet<INItem> INItems { get; set; }
        public virtual DbSet<INPORevertHistory> INPORevertHistories { get; set; }
        public virtual DbSet<INStoreReturnNote> INStoreReturnNotes { get; set; }
        public virtual DbSet<INStoreReturnNoteDetail> INStoreReturnNoteDetails { get; set; }
        public virtual DbSet<INSize> INSizes { get; set; }
        public virtual DbSet<INUnitOfMeasurement> INUnitOfMeasurements { get; set; }
    
        [DbFunction("GLEntities", "fnDVFirstApplicantData")]
        public virtual IQueryable<fnDVFirstApplicantData_Result> fnDVFirstApplicantData(Nullable<int> applicationFormID)
        {
            var applicationFormIDParameter = applicationFormID.HasValue ?
                new ObjectParameter("ApplicationFormID", applicationFormID) :
                new ObjectParameter("ApplicationFormID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDVFirstApplicantData_Result>("[GLEntities].[fnDVFirstApplicantData](@ApplicationFormID)", applicationFormIDParameter);
        }
    
        [DbFunction("GLEntities", "fnDVSecondApplicantData")]
        public virtual IQueryable<fnDVSecondApplicantData_Result> fnDVSecondApplicantData(Nullable<int> applicationFormID)
        {
            var applicationFormIDParameter = applicationFormID.HasValue ?
                new ObjectParameter("ApplicationFormID", applicationFormID) :
                new ObjectParameter("ApplicationFormID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDVSecondApplicantData_Result>("[GLEntities].[fnDVSecondApplicantData](@ApplicationFormID)", applicationFormIDParameter);
        }
    
        [DbFunction("GLEntities", "fnGetApplicant")]
        public virtual IQueryable<fnGetApplicant_Result> fnGetApplicant(Nullable<int> applicantID)
        {
            var applicantIDParameter = applicantID.HasValue ?
                new ObjectParameter("ApplicantID", applicantID) :
                new ObjectParameter("ApplicantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnGetApplicant_Result>("[GLEntities].[fnGetApplicant](@ApplicantID)", applicantIDParameter);
        }
    
        public virtual ObjectResult<spAPInvoiceDetailRows_Result> spAPInvoiceDetailRows(Nullable<long> aPInvoiceID)
        {
            var aPInvoiceIDParameter = aPInvoiceID.HasValue ?
                new ObjectParameter("APInvoiceID", aPInvoiceID) :
                new ObjectParameter("APInvoiceID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAPInvoiceDetailRows_Result>("spAPInvoiceDetailRows", aPInvoiceIDParameter);
        }
    
        public virtual ObjectResult<spAPInvoiceSearchList_Result> spAPInvoiceSearchList(Nullable<int> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAPInvoiceSearchList_Result>("spAPInvoiceSearchList", companyIDParameter);
        }
    
        public virtual ObjectResult<spAPVendorsListWithCode_Result> spAPVendorsListWithCode(Nullable<int> countryID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAPVendorsListWithCode_Result>("spAPVendorsListWithCode", countryIDParameter);
        }
    
        public virtual ObjectResult<spBKBankTransDetailRows_Result> spBKBankTransDetailRows(Nullable<int> bankTransID)
        {
            var bankTransIDParameter = bankTransID.HasValue ?
                new ObjectParameter("BankTransID", bankTransID) :
                new ObjectParameter("BankTransID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBKBankTransDetailRows_Result>("spBKBankTransDetailRows", bankTransIDParameter);
        }
    
        public virtual ObjectResult<spBKBankTransSearchList_Result> spBKBankTransSearchList(Nullable<int> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBKBankTransSearchList_Result>("spBKBankTransSearchList", companyIDParameter);
        }
    
        public virtual ObjectResult<spBSBankStatementPendingUnpendingList_Result> spBSBankStatementPendingUnpendingList(Nullable<int> companyID, Nullable<int> bKBankID, Nullable<bool> isPending, Nullable<System.DateTime> valueDateFrom, Nullable<System.DateTime> valueDateTo)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var bKBankIDParameter = bKBankID.HasValue ?
                new ObjectParameter("BKBankID", bKBankID) :
                new ObjectParameter("BKBankID", typeof(int));
    
            var isPendingParameter = isPending.HasValue ?
                new ObjectParameter("IsPending", isPending) :
                new ObjectParameter("IsPending", typeof(bool));
    
            var valueDateFromParameter = valueDateFrom.HasValue ?
                new ObjectParameter("ValueDateFrom", valueDateFrom) :
                new ObjectParameter("ValueDateFrom", typeof(System.DateTime));
    
            var valueDateToParameter = valueDateTo.HasValue ?
                new ObjectParameter("ValueDateTo", valueDateTo) :
                new ObjectParameter("ValueDateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBSBankStatementPendingUnpendingList_Result>("spBSBankStatementPendingUnpendingList", companyIDParameter, bKBankIDParameter, isPendingParameter, valueDateFromParameter, valueDateToParameter);
        }
    
        public virtual ObjectResult<spBSClassificationHeader_Result> spBSClassificationHeader(Nullable<int> transactionID)
        {
            var transactionIDParameter = transactionID.HasValue ?
                new ObjectParameter("TransactionID", transactionID) :
                new ObjectParameter("TransactionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBSClassificationHeader_Result>("spBSClassificationHeader", transactionIDParameter);
        }
    
        public virtual ObjectResult<spBSClassificationList_Result> spBSClassificationList(Nullable<int> transactionID)
        {
            var transactionIDParameter = transactionID.HasValue ?
                new ObjectParameter("TransactionID", transactionID) :
                new ObjectParameter("TransactionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBSClassificationList_Result>("spBSClassificationList", transactionIDParameter);
        }
    
        public virtual ObjectResult<spBSClassificationSearchList_Result> spBSClassificationSearchList(Nullable<int> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBSClassificationSearchList_Result>("spBSClassificationSearchList", companyIDParameter);
        }
    
        public virtual ObjectResult<spDashboardGetUnitStatusProjectWise_Result> spDashboardGetUnitStatusProjectWise(Nullable<int> companyID, Nullable<int> projectID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDashboardGetUnitStatusProjectWise_Result>("spDashboardGetUnitStatusProjectWise", companyIDParameter, projectIDParameter);
        }
    
        public virtual ObjectResult<spDashboardUnitMatrixProjectWise_Result> spDashboardUnitMatrixProjectWise(Nullable<int> projectID)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDashboardUnitMatrixProjectWise_Result>("spDashboardUnitMatrixProjectWise", projectIDParameter);
        }
    
        public virtual ObjectResult<spDocumentListByApplication_Result> spDocumentListByApplication(Nullable<int> applicationFormID)
        {
            var applicationFormIDParameter = applicationFormID.HasValue ?
                new ObjectParameter("ApplicationFormID", applicationFormID) :
                new ObjectParameter("ApplicationFormID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDocumentListByApplication_Result>("spDocumentListByApplication", applicationFormIDParameter);
        }
    
        public virtual ObjectResult<spDVApplicantRows_Result> spDVApplicantRows(Nullable<int> applicationFormID)
        {
            var applicationFormIDParameter = applicationFormID.HasValue ?
                new ObjectParameter("ApplicationFormID", applicationFormID) :
                new ObjectParameter("ApplicationFormID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVApplicantRows_Result>("spDVApplicantRows", applicationFormIDParameter);
        }
    
        public virtual ObjectResult<spDVApplicationFormSearchList_Result> spDVApplicationFormSearchList(Nullable<int> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVApplicationFormSearchList_Result>("spDVApplicationFormSearchList", companyIDParameter);
        }
    
        public virtual ObjectResult<spDVGetApplicationForm_Result> spDVGetApplicationForm(Nullable<int> applicationFormID)
        {
            var applicationFormIDParameter = applicationFormID.HasValue ?
                new ObjectParameter("ApplicationFormID", applicationFormID) :
                new ObjectParameter("ApplicationFormID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVGetApplicationForm_Result>("spDVGetApplicationForm", applicationFormIDParameter);
        }
    
        public virtual ObjectResult<spDVOBillingDetailRows_Result> spDVOBillingDetailRows(Nullable<int> billingID)
        {
            var billingIDParameter = billingID.HasValue ?
                new ObjectParameter("BillingID", billingID) :
                new ObjectParameter("BillingID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVOBillingDetailRows_Result>("spDVOBillingDetailRows", billingIDParameter);
        }
    
        public virtual ObjectResult<spDVOBillingSearchList_Result> spDVOBillingSearchList(Nullable<int> companyID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> projectID, Nullable<int> unitID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var unitIDParameter = unitID.HasValue ?
                new ObjectParameter("UnitID", unitID) :
                new ObjectParameter("UnitID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVOBillingSearchList_Result>("spDVOBillingSearchList", companyIDParameter, startDateParameter, endDateParameter, projectIDParameter, unitIDParameter);
        }
    
        public virtual ObjectResult<spDVPaymentPlanDetail_Result> spDVPaymentPlanDetail(Nullable<int> paymentPlanID)
        {
            var paymentPlanIDParameter = paymentPlanID.HasValue ?
                new ObjectParameter("PaymentPlanID", paymentPlanID) :
                new ObjectParameter("PaymentPlanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVPaymentPlanDetail_Result>("spDVPaymentPlanDetail", paymentPlanIDParameter);
        }
    
        public virtual ObjectResult<spDVPaymentPlanHead_Result> spDVPaymentPlanHead(Nullable<int> applicationFormID)
        {
            var applicationFormIDParameter = applicationFormID.HasValue ?
                new ObjectParameter("ApplicationFormID", applicationFormID) :
                new ObjectParameter("ApplicationFormID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVPaymentPlanHead_Result>("spDVPaymentPlanHead", applicationFormIDParameter);
        }
    
        public virtual ObjectResult<spDVReceiptDetail_Result> spDVReceiptDetail(Nullable<int> dVReceiptID)
        {
            var dVReceiptIDParameter = dVReceiptID.HasValue ?
                new ObjectParameter("DVReceiptID", dVReceiptID) :
                new ObjectParameter("DVReceiptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVReceiptDetail_Result>("spDVReceiptDetail", dVReceiptIDParameter);
        }
    
        public virtual ObjectResult<spDVReceiptDetailByReceiptID_Result> spDVReceiptDetailByReceiptID(Nullable<int> dVReceiptID)
        {
            var dVReceiptIDParameter = dVReceiptID.HasValue ?
                new ObjectParameter("DVReceiptID", dVReceiptID) :
                new ObjectParameter("DVReceiptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVReceiptDetailByReceiptID_Result>("spDVReceiptDetailByReceiptID", dVReceiptIDParameter);
        }
    
        public virtual ObjectResult<spDVReceiptHead_Result> spDVReceiptHead(Nullable<int> applicationFormID)
        {
            var applicationFormIDParameter = applicationFormID.HasValue ?
                new ObjectParameter("ApplicationFormID", applicationFormID) :
                new ObjectParameter("ApplicationFormID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVReceiptHead_Result>("spDVReceiptHead", applicationFormIDParameter);
        }
    
        public virtual ObjectResult<spDVReceiptHeadByReceiptID_Result> spDVReceiptHeadByReceiptID(Nullable<int> dVReceiptID)
        {
            var dVReceiptIDParameter = dVReceiptID.HasValue ?
                new ObjectParameter("DVReceiptID", dVReceiptID) :
                new ObjectParameter("DVReceiptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVReceiptHeadByReceiptID_Result>("spDVReceiptHeadByReceiptID", dVReceiptIDParameter);
        }
    
        public virtual ObjectResult<spDVReceiptSearchList_Result> spDVReceiptSearchList(Nullable<int> companyID, Nullable<int> projectID, Nullable<int> unitID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var unitIDParameter = unitID.HasValue ?
                new ObjectParameter("UnitID", unitID) :
                new ObjectParameter("UnitID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVReceiptSearchList_Result>("spDVReceiptSearchList", companyIDParameter, projectIDParameter, unitIDParameter);
        }
    
        public virtual ObjectResult<spDVReceiptSearchListSGO_Result> spDVReceiptSearchListSGO(Nullable<int> companyID, Nullable<int> projectID, Nullable<int> unitID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var unitIDParameter = unitID.HasValue ?
                new ObjectParameter("UnitID", unitID) :
                new ObjectParameter("UnitID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVReceiptSearchListSGO_Result>("spDVReceiptSearchListSGO", companyIDParameter, projectIDParameter, unitIDParameter);
        }
    
        public virtual ObjectResult<spDVUnitsListByProjectID_Result> spDVUnitsListByProjectID(Nullable<int> projectID, Nullable<bool> allUnits)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var allUnitsParameter = allUnits.HasValue ?
                new ObjectParameter("AllUnits", allUnits) :
                new ObjectParameter("AllUnits", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVUnitsListByProjectID_Result>("spDVUnitsListByProjectID", projectIDParameter, allUnitsParameter);
        }
    
        public virtual ObjectResult<spDVUnitsRows_Result> spDVUnitsRows(Nullable<int> unitID)
        {
            var unitIDParameter = unitID.HasValue ?
                new ObjectParameter("UnitID", unitID) :
                new ObjectParameter("UnitID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDVUnitsRows_Result>("spDVUnitsRows", unitIDParameter);
        }
    
        public virtual ObjectResult<spFiscalYearSetupGetList_Result> spFiscalYearSetupGetList(Nullable<int> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFiscalYearSetupGetList_Result>("spFiscalYearSetupGetList", companyIDParameter);
        }
    
        public virtual ObjectResult<spGetMenuPages_Result> spGetMenuPages(Nullable<int> companyID, Nullable<int> userID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetMenuPages_Result>("spGetMenuPages", companyIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<spGLAccountsForDropdown_Result> spGLAccountsForDropdown(Nullable<int> countryID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGLAccountsForDropdown_Result>("spGLAccountsForDropdown", countryIDParameter);
        }
    
        public virtual ObjectResult<spGLVoucherDetailRows_Result> spGLVoucherDetailRows(Nullable<int> companyID, Nullable<int> gLVoucherID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var gLVoucherIDParameter = gLVoucherID.HasValue ?
                new ObjectParameter("GLVoucherID", gLVoucherID) :
                new ObjectParameter("GLVoucherID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGLVoucherDetailRows_Result>("spGLVoucherDetailRows", companyIDParameter, gLVoucherIDParameter);
        }
    
        public virtual ObjectResult<spGLVoucherGetByID_Result> spGLVoucherGetByID(Nullable<int> voucherID)
        {
            var voucherIDParameter = voucherID.HasValue ?
                new ObjectParameter("VoucherID", voucherID) :
                new ObjectParameter("VoucherID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGLVoucherGetByID_Result>("spGLVoucherGetByID", voucherIDParameter);
        }
    
        public virtual ObjectResult<spGLVoucherSearchList_Result> spGLVoucherSearchList(Nullable<int> companyID, Nullable<int> voucherTypeID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var voucherTypeIDParameter = voucherTypeID.HasValue ?
                new ObjectParameter("VoucherTypeID", voucherTypeID) :
                new ObjectParameter("VoucherTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGLVoucherSearchList_Result>("spGLVoucherSearchList", companyIDParameter, voucherTypeIDParameter);
        }
    
        public virtual ObjectResult<spINGetItemRow_Result> spINGetItemRow(Nullable<int> projectID, Nullable<long> itemID)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINGetItemRow_Result>("spINGetItemRow", projectIDParameter, itemIDParameter);
        }
    
        public virtual ObjectResult<spINItemSearchList_Result> spINItemSearchList(string itemCode, Nullable<int> groupID, string description)
        {
            var itemCodeParameter = itemCode != null ?
                new ObjectParameter("ItemCode", itemCode) :
                new ObjectParameter("ItemCode", typeof(string));
    
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINItemSearchList_Result>("spINItemSearchList", itemCodeParameter, groupIDParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<spINPurchaseRequisitionDetailRows_Result> spINPurchaseRequisitionDetailRows(Nullable<int> requestID)
        {
            var requestIDParameter = requestID.HasValue ?
                new ObjectParameter("RequestID", requestID) :
                new ObjectParameter("RequestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINPurchaseRequisitionDetailRows_Result>("spINPurchaseRequisitionDetailRows", requestIDParameter);
        }
    
        public virtual ObjectResult<spINStoreIssueNoteDetailRows_Result> spINStoreIssueNoteDetailRows(Nullable<int> storeIssueNoteID)
        {
            var storeIssueNoteIDParameter = storeIssueNoteID.HasValue ?
                new ObjectParameter("StoreIssueNoteID", storeIssueNoteID) :
                new ObjectParameter("StoreIssueNoteID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINStoreIssueNoteDetailRows_Result>("spINStoreIssueNoteDetailRows", storeIssueNoteIDParameter);
        }
    
        public virtual ObjectResult<spIntDVReceiptCash_Result> spIntDVReceiptCash(Nullable<int> dVReceiptID)
        {
            var dVReceiptIDParameter = dVReceiptID.HasValue ?
                new ObjectParameter("DVReceiptID", dVReceiptID) :
                new ObjectParameter("DVReceiptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spIntDVReceiptCash_Result>("spIntDVReceiptCash", dVReceiptIDParameter);
        }
    
        public virtual ObjectResult<spLoginUser_Result> spLoginUser(Nullable<int> companyID, Nullable<int> userID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLoginUser_Result>("spLoginUser", companyIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<spMenuPagesRights_Result> spMenuPagesRights(Nullable<int> companyID, Nullable<bool> isAdmin)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMenuPagesRights_Result>("spMenuPagesRights", companyIDParameter, isAdminParameter);
        }
    
        public virtual ObjectResult<spMenuPagesRightsList_Result> spMenuPagesRightsList(Nullable<int> companyID, Nullable<int> userID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMenuPagesRightsList_Result>("spMenuPagesRightsList", companyIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<spRptAPPartyLedger_Result> spRptAPPartyLedger(Nullable<int> companyID, Nullable<System.DateTime> toDate, Nullable<int> aPVendorID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var aPVendorIDParameter = aPVendorID.HasValue ?
                new ObjectParameter("APVendorID", aPVendorID) :
                new ObjectParameter("APVendorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptAPPartyLedger_Result>("spRptAPPartyLedger", companyIDParameter, toDateParameter, aPVendorIDParameter);
        }
    
        public virtual ObjectResult<spRptDVApplication_Result> spRptDVApplication(Nullable<int> applicationFormID)
        {
            var applicationFormIDParameter = applicationFormID.HasValue ?
                new ObjectParameter("ApplicationFormID", applicationFormID) :
                new ObjectParameter("ApplicationFormID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptDVApplication_Result>("spRptDVApplication", applicationFormIDParameter);
        }
    
        public virtual ObjectResult<spRptDVReceipt_Result> spRptDVReceipt(Nullable<int> dVReceiptID)
        {
            var dVReceiptIDParameter = dVReceiptID.HasValue ?
                new ObjectParameter("DVReceiptID", dVReceiptID) :
                new ObjectParameter("DVReceiptID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptDVReceipt_Result>("spRptDVReceipt", dVReceiptIDParameter);
        }
    
        public virtual ObjectResult<spRptDVUnitLedger_Result> spRptDVUnitLedger(Nullable<int> projectID, Nullable<int> unitID, Nullable<System.DateTime> toDate)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var unitIDParameter = unitID.HasValue ?
                new ObjectParameter("UnitID", unitID) :
                new ObjectParameter("UnitID", typeof(int));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptDVUnitLedger_Result>("spRptDVUnitLedger", projectIDParameter, unitIDParameter, toDateParameter);
        }
    
        public virtual ObjectResult<spRptGeneralLedger_Result> spRptGeneralLedger(Nullable<int> companyID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string startGLAccountNo, string endGLAccountNo)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var startGLAccountNoParameter = startGLAccountNo != null ?
                new ObjectParameter("StartGLAccountNo", startGLAccountNo) :
                new ObjectParameter("StartGLAccountNo", typeof(string));
    
            var endGLAccountNoParameter = endGLAccountNo != null ?
                new ObjectParameter("EndGLAccountNo", endGLAccountNo) :
                new ObjectParameter("EndGLAccountNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptGeneralLedger_Result>("spRptGeneralLedger", companyIDParameter, startDateParameter, endDateParameter, startGLAccountNoParameter, endGLAccountNoParameter);
        }
    
        public virtual ObjectResult<spRptGeneralLedgerOB_Result> spRptGeneralLedgerOB(Nullable<int> companyID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string startGLAccountNo, string endGLAccountNo)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var startGLAccountNoParameter = startGLAccountNo != null ?
                new ObjectParameter("StartGLAccountNo", startGLAccountNo) :
                new ObjectParameter("StartGLAccountNo", typeof(string));
    
            var endGLAccountNoParameter = endGLAccountNo != null ?
                new ObjectParameter("EndGLAccountNo", endGLAccountNo) :
                new ObjectParameter("EndGLAccountNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptGeneralLedgerOB_Result>("spRptGeneralLedgerOB", companyIDParameter, startDateParameter, endDateParameter, startGLAccountNoParameter, endGLAccountNoParameter);
        }
    
        public virtual ObjectResult<spRptGLTrialBalance_Result> spRptGLTrialBalance(Nullable<int> companyID, string fiscalYear)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var fiscalYearParameter = fiscalYear != null ?
                new ObjectParameter("FiscalYear", fiscalYear) :
                new ObjectParameter("FiscalYear", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptGLTrialBalance_Result>("spRptGLTrialBalance", companyIDParameter, fiscalYearParameter);
        }
    
        public virtual ObjectResult<spRptGLVoucherGetByID_Result> spRptGLVoucherGetByID(Nullable<int> voucherID)
        {
            var voucherIDParameter = voucherID.HasValue ?
                new ObjectParameter("VoucherID", voucherID) :
                new ObjectParameter("VoucherID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptGLVoucherGetByID_Result>("spRptGLVoucherGetByID", voucherIDParameter);
        }
    
        public virtual ObjectResult<spRptMemberPaymentPlanStatus_AllUnits_Result> spRptMemberPaymentPlanStatus_AllUnits(Nullable<int> projectID, Nullable<System.DateTime> statusDate)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var statusDateParameter = statusDate.HasValue ?
                new ObjectParameter("StatusDate", statusDate) :
                new ObjectParameter("StatusDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptMemberPaymentPlanStatus_AllUnits_Result>("spRptMemberPaymentPlanStatus_AllUnits", projectIDParameter, statusDateParameter);
        }
    
        public virtual ObjectResult<spRptMemberPaymentPlanStatus_PaymentPlan_Result> spRptMemberPaymentPlanStatus_PaymentPlan(Nullable<int> projectID, Nullable<int> unitID, Nullable<System.DateTime> statusDate)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var unitIDParameter = unitID.HasValue ?
                new ObjectParameter("UnitID", unitID) :
                new ObjectParameter("UnitID", typeof(int));
    
            var statusDateParameter = statusDate.HasValue ?
                new ObjectParameter("StatusDate", statusDate) :
                new ObjectParameter("StatusDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptMemberPaymentPlanStatus_PaymentPlan_Result>("spRptMemberPaymentPlanStatus_PaymentPlan", projectIDParameter, unitIDParameter, statusDateParameter);
        }
    
        public virtual ObjectResult<spRptMemberPaymentPlanStatus_Receipt_Result> spRptMemberPaymentPlanStatus_Receipt(Nullable<int> projectID, Nullable<int> unitID)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var unitIDParameter = unitID.HasValue ?
                new ObjectParameter("UnitID", unitID) :
                new ObjectParameter("UnitID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptMemberPaymentPlanStatus_Receipt_Result>("spRptMemberPaymentPlanStatus_Receipt", projectIDParameter, unitIDParameter);
        }
    
        public virtual ObjectResult<spRptPaymentPlan_Result> spRptPaymentPlan(Nullable<int> paymentPlanID)
        {
            var paymentPlanIDParameter = paymentPlanID.HasValue ?
                new ObjectParameter("PaymentPlanID", paymentPlanID) :
                new ObjectParameter("PaymentPlanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptPaymentPlan_Result>("spRptPaymentPlan", paymentPlanIDParameter);
        }
    
        public virtual ObjectResult<spSecurityGetModuleIdsByUser_Result> spSecurityGetModuleIdsByUser(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSecurityGetModuleIdsByUser_Result>("spSecurityGetModuleIdsByUser", userIDParameter);
        }
    
        public virtual ObjectResult<spSecUserGetSearchList_Result> spSecUserGetSearchList(Nullable<int> companyID, Nullable<long> userID, string name, string username, Nullable<short> statusTypeID, Nullable<short> roleID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var statusTypeIDParameter = statusTypeID.HasValue ?
                new ObjectParameter("StatusTypeID", statusTypeID) :
                new ObjectParameter("StatusTypeID", typeof(short));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSecUserGetSearchList_Result>("spSecUserGetSearchList", companyIDParameter, userIDParameter, nameParameter, usernameParameter, statusTypeIDParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<spUserPagesRights_Result> spUserPagesRights(Nullable<short> companyID, Nullable<int> userID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(short));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUserPagesRights_Result>("spUserPagesRights", companyIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<spRptMemberPaymentPlanStatus_PaymentPlan_AllUnits_Result> spRptMemberPaymentPlanStatus_PaymentPlan_AllUnits(Nullable<int> projectID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptMemberPaymentPlanStatus_PaymentPlan_AllUnits_Result>("spRptMemberPaymentPlanStatus_PaymentPlan_AllUnits", projectIDParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<spRptMemberPaymentPlanStatus_Receipt_AllUnits_Result> spRptMemberPaymentPlanStatus_Receipt_AllUnits(Nullable<int> projectID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptMemberPaymentPlanStatus_Receipt_AllUnits_Result>("spRptMemberPaymentPlanStatus_Receipt_AllUnits", projectIDParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<spINStoreIssueNoteItemRow_Result> spINStoreIssueNoteItemRow(Nullable<long> itemID)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINStoreIssueNoteItemRow_Result>("spINStoreIssueNoteItemRow", itemIDParameter);
        }
    
        public virtual ObjectResult<spRptINItemStock_Result> spRptINItemStock(Nullable<int> companyID, Nullable<int> projectID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptINItemStock_Result>("spRptINItemStock", companyIDParameter, projectIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<spINStoreTransferNoteDetailRows_Result> spINStoreTransferNoteDetailRows(Nullable<int> storeTransferNoteID)
        {
            var storeTransferNoteIDParameter = storeTransferNoteID.HasValue ?
                new ObjectParameter("StoreTransferNoteID", storeTransferNoteID) :
                new ObjectParameter("StoreTransferNoteID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINStoreTransferNoteDetailRows_Result>("spINStoreTransferNoteDetailRows", storeTransferNoteIDParameter);
        }
    
        public virtual ObjectResult<spINStoreIssueNoteItemsDropdown_Result> spINStoreIssueNoteItemsDropdown(Nullable<int> projectID, Nullable<int> companyID)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINStoreIssueNoteItemsDropdown_Result>("spINStoreIssueNoteItemsDropdown", projectIDParameter, companyIDParameter);
        }
    
        public virtual ObjectResult<spRptINStoreTransferNote_Result> spRptINStoreTransferNote(Nullable<int> storeTransferNoteID)
        {
            var storeTransferNoteIDParameter = storeTransferNoteID.HasValue ?
                new ObjectParameter("StoreTransferNoteID", storeTransferNoteID) :
                new ObjectParameter("StoreTransferNoteID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptINStoreTransferNote_Result>("spRptINStoreTransferNote", storeTransferNoteIDParameter);
        }
    
        public virtual ObjectResult<spINGetGRNItemRow_Result> spINGetGRNItemRow(Nullable<long> itemID, Nullable<long> requestDetailID)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            var requestDetailIDParameter = requestDetailID.HasValue ?
                new ObjectParameter("RequestDetailID", requestDetailID) :
                new ObjectParameter("RequestDetailID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINGetGRNItemRow_Result>("spINGetGRNItemRow", itemIDParameter, requestDetailIDParameter);
        }
    
        public virtual ObjectResult<spRptINPurchaseRequisition_Result> spRptINPurchaseRequisition(Nullable<int> requestID)
        {
            var requestIDParameter = requestID.HasValue ?
                new ObjectParameter("RequestID", requestID) :
                new ObjectParameter("RequestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptINPurchaseRequisition_Result>("spRptINPurchaseRequisition", requestIDParameter);
        }
    
        public virtual ObjectResult<spINPRItemsDropdown_Result> spINPRItemsDropdown(Nullable<long> requestID)
        {
            var requestIDParameter = requestID.HasValue ?
                new ObjectParameter("RequestID", requestID) :
                new ObjectParameter("RequestID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINPRItemsDropdown_Result>("spINPRItemsDropdown", requestIDParameter);
        }
    
        public virtual ObjectResult<spINGetPRItemRowForPO_Result> spINGetPRItemRowForPO(Nullable<long> itemID, Nullable<long> requestDetailID)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            var requestDetailIDParameter = requestDetailID.HasValue ?
                new ObjectParameter("RequestDetailID", requestDetailID) :
                new ObjectParameter("RequestDetailID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINGetPRItemRowForPO_Result>("spINGetPRItemRowForPO", itemIDParameter, requestDetailIDParameter);
        }
    
        public virtual ObjectResult<spRptINGoodsReceiptNote_Result> spRptINGoodsReceiptNote(Nullable<long> goodsReceiptNoteID)
        {
            var goodsReceiptNoteIDParameter = goodsReceiptNoteID.HasValue ?
                new ObjectParameter("GoodsReceiptNoteID", goodsReceiptNoteID) :
                new ObjectParameter("GoodsReceiptNoteID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptINGoodsReceiptNote_Result>("spRptINGoodsReceiptNote", goodsReceiptNoteIDParameter);
        }
    
        public virtual ObjectResult<spINGRNItemsForPODropdown_Result> spINGRNItemsForPODropdown(Nullable<long> goodsReceiptNoteID)
        {
            var goodsReceiptNoteIDParameter = goodsReceiptNoteID.HasValue ?
                new ObjectParameter("GoodsReceiptNoteID", goodsReceiptNoteID) :
                new ObjectParameter("GoodsReceiptNoteID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINGRNItemsForPODropdown_Result>("spINGRNItemsForPODropdown", goodsReceiptNoteIDParameter);
        }
    
        public virtual ObjectResult<spINGRNItemsDropdown_Result> spINGRNItemsDropdown(Nullable<int> companyID, Nullable<int> projectID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINGRNItemsDropdown_Result>("spINGRNItemsDropdown", companyIDParameter, projectIDParameter);
        }
    
        public virtual ObjectResult<spINGoodsReceiptNoteWithoutPOSearchList_Result> spINGoodsReceiptNoteWithoutPOSearchList(Nullable<int> companyID, Nullable<int> userID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINGoodsReceiptNoteWithoutPOSearchList_Result>("spINGoodsReceiptNoteWithoutPOSearchList", companyIDParameter, userIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<spRptINGoodsReceiptNoteHistoryData_Result> spRptINGoodsReceiptNoteHistoryData(Nullable<int> projectID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptINGoodsReceiptNoteHistoryData_Result>("spRptINGoodsReceiptNoteHistoryData", projectIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<spRptINPurchaseRequisitionHistoryData_Result> spRptINPurchaseRequisitionHistoryData(Nullable<int> projectID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptINPurchaseRequisitionHistoryData_Result>("spRptINPurchaseRequisitionHistoryData", projectIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<spINPurchaseOrderDetailRows_Result> spINPurchaseOrderDetailRows(Nullable<int> iNPurchaseOrderID)
        {
            var iNPurchaseOrderIDParameter = iNPurchaseOrderID.HasValue ?
                new ObjectParameter("INPurchaseOrderID", iNPurchaseOrderID) :
                new ObjectParameter("INPurchaseOrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINPurchaseOrderDetailRows_Result>("spINPurchaseOrderDetailRows", iNPurchaseOrderIDParameter);
        }
    
        public virtual ObjectResult<spRptINPurchaseOrder_Result> spRptINPurchaseOrder(Nullable<long> purchaseOrderID)
        {
            var purchaseOrderIDParameter = purchaseOrderID.HasValue ?
                new ObjectParameter("PurchaseOrderID", purchaseOrderID) :
                new ObjectParameter("PurchaseOrderID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptINPurchaseOrder_Result>("spRptINPurchaseOrder", purchaseOrderIDParameter);
        }
    
        public virtual ObjectResult<spRptINPORevertHistoryData_Result> spRptINPORevertHistoryData(Nullable<int> projectID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptINPORevertHistoryData_Result>("spRptINPORevertHistoryData", projectIDParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<spINStoreReturnNoteDetailRows_Result> spINStoreReturnNoteDetailRows(Nullable<int> storeReturnNoteID)
        {
            var storeReturnNoteIDParameter = storeReturnNoteID.HasValue ?
                new ObjectParameter("StoreReturnNoteID", storeReturnNoteID) :
                new ObjectParameter("StoreReturnNoteID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINStoreReturnNoteDetailRows_Result>("spINStoreReturnNoteDetailRows", storeReturnNoteIDParameter);
        }
    
        public virtual ObjectResult<spINItemsDropdown_Result> spINItemsDropdown(Nullable<int> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINItemsDropdown_Result>("spINItemsDropdown", companyIDParameter);
        }
    
        public virtual ObjectResult<spINStoreReturnNoteItemRow_Result> spINStoreReturnNoteItemRow(Nullable<long> itemID)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINStoreReturnNoteItemRow_Result>("spINStoreReturnNoteItemRow", itemIDParameter);
        }
    
        public virtual ObjectResult<spRptINStoreIssueNote_Result> spRptINStoreIssueNote(Nullable<int> storeIssueNoteID)
        {
            var storeIssueNoteIDParameter = storeIssueNoteID.HasValue ?
                new ObjectParameter("StoreIssueNoteID", storeIssueNoteID) :
                new ObjectParameter("StoreIssueNoteID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptINStoreIssueNote_Result>("spRptINStoreIssueNote", storeIssueNoteIDParameter);
        }
    
        public virtual ObjectResult<spRptINStoreReturnNote_Result> spRptINStoreReturnNote(Nullable<int> storeReturnNoteID)
        {
            var storeReturnNoteIDParameter = storeReturnNoteID.HasValue ?
                new ObjectParameter("StoreReturnNoteID", storeReturnNoteID) :
                new ObjectParameter("StoreReturnNoteID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spRptINStoreReturnNote_Result>("spRptINStoreReturnNote", storeReturnNoteIDParameter);
        }
    
        public virtual ObjectResult<spBKBankTransSearchList1_Result> spBKBankTransSearchList1(Nullable<int> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBKBankTransSearchList1_Result>("spBKBankTransSearchList1", companyIDParameter);
        }
    
        public virtual ObjectResult<spINGoodsReceiptNoteSearchList_Result> spINGoodsReceiptNoteSearchList(Nullable<int> companyID, Nullable<int> userID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<long> itemID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINGoodsReceiptNoteSearchList_Result>("spINGoodsReceiptNoteSearchList", companyIDParameter, userIDParameter, fromDateParameter, toDateParameter, itemIDParameter);
        }
    
        public virtual ObjectResult<spINPurchaseOrderSearchList_Result> spINPurchaseOrderSearchList(Nullable<int> companyID, Nullable<int> userID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<long> itemID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINPurchaseOrderSearchList_Result>("spINPurchaseOrderSearchList", companyIDParameter, userIDParameter, fromDateParameter, toDateParameter, itemIDParameter);
        }
    
        public virtual ObjectResult<spINPurchaseRequisitionSearchList_Result> spINPurchaseRequisitionSearchList(Nullable<int> companyID, Nullable<int> userID, Nullable<System.DateTime> requestDateFrom, Nullable<System.DateTime> requestDateTo, Nullable<long> itemID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var requestDateFromParameter = requestDateFrom.HasValue ?
                new ObjectParameter("RequestDateFrom", requestDateFrom) :
                new ObjectParameter("RequestDateFrom", typeof(System.DateTime));
    
            var requestDateToParameter = requestDateTo.HasValue ?
                new ObjectParameter("RequestDateTo", requestDateTo) :
                new ObjectParameter("RequestDateTo", typeof(System.DateTime));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINPurchaseRequisitionSearchList_Result>("spINPurchaseRequisitionSearchList", companyIDParameter, userIDParameter, requestDateFromParameter, requestDateToParameter, itemIDParameter);
        }
    
        public virtual ObjectResult<spINStoreIssueNoteSearchList_Result> spINStoreIssueNoteSearchList(Nullable<int> companyID, Nullable<int> userID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<long> itemID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINStoreIssueNoteSearchList_Result>("spINStoreIssueNoteSearchList", companyIDParameter, userIDParameter, fromDateParameter, toDateParameter, itemIDParameter);
        }
    
        public virtual ObjectResult<spINStoreReturnNoteSearchList_Result> spINStoreReturnNoteSearchList(Nullable<int> companyID, Nullable<int> userID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<long> itemID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINStoreReturnNoteSearchList_Result>("spINStoreReturnNoteSearchList", companyIDParameter, userIDParameter, fromDateParameter, toDateParameter, itemIDParameter);
        }
    
        public virtual ObjectResult<spINStoreTransferNoteSearchList_Result> spINStoreTransferNoteSearchList(Nullable<int> companyID, Nullable<int> userID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<long> itemID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINStoreTransferNoteSearchList_Result>("spINStoreTransferNoteSearchList", companyIDParameter, userIDParameter, fromDateParameter, toDateParameter, itemIDParameter);
        }
    
        public virtual ObjectResult<spINGoodsReceiptNoteDetailRows_Result> spINGoodsReceiptNoteDetailRows(Nullable<int> goodsReceiptNoteID)
        {
            var goodsReceiptNoteIDParameter = goodsReceiptNoteID.HasValue ?
                new ObjectParameter("GoodsReceiptNoteID", goodsReceiptNoteID) :
                new ObjectParameter("GoodsReceiptNoteID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINGoodsReceiptNoteDetailRows_Result>("spINGoodsReceiptNoteDetailRows", goodsReceiptNoteIDParameter);
        }
    }
}
