//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecPage
    {
        public int PageID { get; set; }
        public Nullable<int> ModuleNo { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string PageName { get; set; }
        public string PageUrl { get; set; }
    }
}
