//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecPagesRight
    {
        public int PageRightsID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ModuleNo { get; set; }
        public Nullable<int> ModuleOrderNo { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<int> PageOrderNo { get; set; }
        public Nullable<bool> IsViewAllowed { get; set; }
        public Nullable<bool> IsAddAllowed { get; set; }
        public Nullable<bool> IsEditAllowed { get; set; }
        public Nullable<bool> IsDeleteAllowed { get; set; }
        public Nullable<bool> IsPrintAllowed { get; set; }
    }
}
