//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecUserRole
    {
        public long UserRoleID { get; set; }
        public long UserID { get; set; }
        public int RoleID { get; set; }
    
        public virtual SecRole SecRole { get; set; }
    }
}
