//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecUser
    {
        public int UsersID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string Name { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<short> StatusTypeID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
