//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherType
    {
        public int VoucherTypeID { get; set; }
        public string Module { get; set; }
        public string Type { get; set; }
        public Nullable<int> MODTYPE { get; set; }
        public string VTYPE { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
